In [1]:
import pandas as pd
my_books = pd.read_csv("liked_books.csv", index_col = 0)

In [2]:
my_books

,user_id,book_id,rating,title
0,-1,2517439,5,"The Forever War (The Forever War, #1)"
1,-1,113576,5,The Smartest Guys in the Room: The Amazing Ris...
2,-1,35100,5,Battle Cry of Freedom
3,-1,228221,5,The Mask of Command
4,-1,17662739,5,"2001: A Space Odyssey (Space Odyssey, #1)"
...,...,...,...,...
523,-1,28187,1,The Lightning Thief (Percy Jackson and the Ol...
524,-1,7094569,1,"Feed (Newsflesh, #1)"
525,-1,18925933,1,Mastering the VC Game: A Venture Capital Insid...
526,-1,25659450,1,Arkwright
527,-1,82599,1,Rabbits: A Novel

In [3]:
my_books["book_id"] = my_books["book_id"].astype(str)

In [4]:
my_books

,user_id,book_id,rating,title
0,-1,2517439,5,"The Forever War (The Forever War, #1)"
1,-1,113576,5,The Smartest Guys in the Room: The Amazing Ris...
2,-1,35100,5,Battle Cry of Freedom
3,-1,228221,5,The Mask of Command
4,-1,17662739,5,"2001: A Space Odyssey (Space Odyssey, #1)"
...,...,...,...,...
523,-1,28187,1,The Lightning Thief (Percy Jackson and the Ol...
524,-1,7094569,1,"Feed (Newsflesh, #1)"
525,-1,18925933,1,Mastering the VC Game: A Venture Capital Insid...
526,-1,25659450,1,Arkwright
527,-1,82599,1,Rabbits: A Novel

In [5]:
csv_book_mapping = {}

with open("book_id_map.csv", "r") as f:
    while True:
        line = f.readline()
        if not line:
            break
        csv_id, book_id = line.strip().split(",")
        csv_book_mapping[csv_id] = book_id

In [6]:
book_set = set(my_books["book_id"])

In [7]:
book_set

{'1001524',
 '100467',
 '10176',
 '10194157',
 '102327',
 '10240738',
 '10373853',
 '10506237',
 '10664113',
 '10669',
 '1069143',
 '10790277',
 '10790290',
 '10803709',
 '10904853',
 '1105422',
 '1107296',
 '1107306',
 '1122023',
 '112292',
 '112537',
 '1126719',
 '11271034',
 '113047',
 '113224',
 '11343467',
 '11354791',
 '113576',
 '11357844',
 '11366',
 '113934',
 '114217',
 '11472',
 '116356',
 '116446',
 '1166599',
 '1167532',
 '118565',
 '11864578',
 '11865558',
 '1189454',
 '11986736',
 '12007',
 '12016',
 '12090838',
 '12099136',
 '12125412',
 '1215032',
 '12382340',
 '123933',
 '1260131',
 '12609433',
 '12661',
 '127455',
 '127888',
 '128029',
 '1281235',
 '12856474',
 '12891107',
 '12975375',
 '12997490',
 '13055592',
 '13101468',
 '13153693',
 '13372977',
 '13418329',
 '13452375',
 '13453029',
 '13490776',
 '13569815',
 '13573419',
 '13616278',
 '136251',
 '13707738',
 '1372055',
 '13812',
 '139069',
 '139373',
 '140671',
 '1430426',
 '14563',
 '149267',
 '149847',
 '15034320',
 '156534',
 '15704459',
 '15730052',
 '15750692',
 '15790883',
 '15790894',
 '15810910',
 '15839976',
 '15944410',
 '15995144',
 '16007873',
 '16080547',
 '16115612',
 '16130312',
 '161456',
 '16158601',
 '1633',
 '1635',
 '1649029',
 '16690',
 '167847',
 '1685995',
 '169651',
 '1705697',
 '17118699',
 '17182126',
 '17214',
 '17255186',
 '17306293',
 '17314923',
 '17332218',
 '17333324',
 '174501',
 '17554595',
 '17568801',
 '17662739',
 '1768603',
 '17702284',
 '17910124',
 '17934530',
 '17999892',
 '180463',
 '18077903',
 '18138189',
 '18163529',
 '18176747',
 '18241129',
 '18242950',
 '1839',
 '18453098',
 '18460193',
 '18490567',
 '18505792',
 '18626839',
 '18630',
 '18635622',
 '18656030',
 '18656827',
 '18663149',
 '18693655',
 '18693884',
 '18775365',
 '18903906',
 '18925933',
 '1894269',
 '18949861',
 '18952341',
 '1898',
 '1911',
 '19161852',
 '19400',
 '19694475',
 '19785919',
 '1993860',
 '20168816',
 '2036093',
 '20416357',
 '20509356',
 '20556791',
 '20645163',
 '20673694',
 '20697413',
 '20706317',
 '20763746',
 '20787425',
 '20873740',
 '2087754',
 '20878',
 '20879524',
 '20957438',
 '212890',
 '21343',
 '21535271',
 '21611',
 '2191152',
 '2192092',
 '22297138',
 '22328',
 '223380',
 '22435',
 '224379',
 '22544764',
 '226004',
 '2271968',
 '22733729',
 '22814387',
 '22816087',
 '228221',
 '22822848',
 '22859850',
 '228665',
 '22878967',
 '22886612',
 '2315892',
 '231622',
 '23164927',
 '23168817',
 '23197269',
 '23208397',
 '23357063',
 '233679',
 '23444482',
 '234503',
 '23562877',
 '2372',
 '239796',
 '23986891',
 '240617',
 '24249',
 '24474911',
 '24611565',
 '24611668',
 '24614',
 '24830',
 '24856109',
 '24874360',
 '24876258',
 '248787',
 '25016389',
 '25111328',
 '2517439',
 '25300956',
 '25318',
 '25320',
 '25451264',
 '25499718',
 '25602451',
 '25656228',
 '25659450',
 '25689056',
 '25733990',
 '25744928',
 '25817395',
 '25852860',
 '25895524',
 '25938481',
 '26030703',
 '26114416',
 '26114545',
 '26118426',
 '26156469',
 '26228034',
 '26569995',
 '26892143',
 '270032',
 '27071490',
 '27161156',
 '2723',
 '2732977',
 '27507117',
 '2790566',
 '28165439',
 '28186',
 '28187',
 '2820512',
 '28259132',
 '284658',
 '284873',
 '28530221',
 '285451',
 '285591',
 '286445',
 '2890090',
 '28962452',
 '28962895',
 '290186',
 '29125925',
 '29133',
 '2913377',
 '292327',
 '292570',
 '29496076',
 '29570143',
 '29580',
 '29581',
 '2978',
 '29983711',
 '30007916',
 '30078567',
 '30139664',
 '30231729',
 '30237009',
 '30316148',
 '30329506',
 '306090',
 '30689366',
 '30762503',
 '30841984',
 '31176804',
 '31423188',
 '315939',
 '31687423',
 '31817749',
 '32081',
 '32424',
 '324750',
 '32508',
 '32605183',
 '32735037',
 '33132474',
 '3335194',
 '333867',
 '3363015',
 '33635374',
 '3428935',
 '3437328',
 '34494',
 '34497',
 '34506',
 '350',
 '35100',
 '35128447',
 '356824',
 '357486',
 '3607898',
 '36194',
 '362550',
 '36313',
 '3636',
 '3760025',
 '386366',
 '386372',
 '386373',
 '386374',
 '386579',
 '3869',
 '3896708',
 '39020',
 '399415',
 '400881',
 '400906',
 '40445',
 '406911',
 '409207',
 '40992',
 '4122',
 '419083',
 '42000',
 '437143',
 '44659',
 '45109',
 '45245',
 '45258',
 '45260',
 '454614',
 '46654',
 '46756',
 '47109',
 '474072',
 '475',
 '477380',
 '479561',
 '481335',
 '49116',
 '49174',
 '4952',
 '49869',
 '50027',
 '502230',
 '5043',
 '504366',
 '504369',
 '5061675',
 '5064',
 '507932',
 '5096865',
 '522776',
 '52397',
 '528362',
 '528366',
 '5325066',
 '5439',
 '55067',
 '5558786',
 '556180',
 '5578108',
 '563469',
 '569978',
 '57096',
 '59660',
 '5979072',
 '6043781',
 '6065629',
 '6068557',
 '60932',
 '6101718',
 '61179',
 '61642',
 '6178648',
 '618221',
 '618241',
 '61905',
 '61906',
 '61916',
 '6219313',
 '62992',
 '6336986',
 '6341533',
 '6387626',
 '6391993',
 '64222',
 '6424171',
 '6448772',
 '645023',
 '6458635',
 '6466554',
 '655707',
 '6569735',
 '6605625',
 '66559',
 '66678',
 '66717',
 '673158',
 '6736971',
 '6753849',
 '6792458',
 '6794',
 '6828896',
 '68428',
 '68487',
 '6928839',
 '6963184',
 '7094569',
 '7108725',
 '71135',
 '7137787',
 '7141642',
 '7165300',
 '7234921',
 '7315573',
 '7326427',
 '7438179',
 '7613',
 '763362',
 '76405',
 '76479',
 '76680',
 '767171',
 '76740',
 '77203',
 '7743175',
 '77505',
 '77507',
 '77565',
 '776212',
 '77711',
 '77735',
 '77736',
 '77739',
 '77740',
 '77747',
 '781182',
 '79909',
 '7996',
 '80955',
 '8117586',
 '8136985',
 '8141748',
 '8161140',
 '8171378',
 '8173788',
 '8176890',
 '818145',
 '81948',
 '8253920',
 '82599',
 '8302734',
 '8302746',
 '830616',
 '840278',
 '8428984',
 '8442457',
 '846092',
 '857043',
 '866136',
 '8683527',
 '873486',
 '883438',
 '8837',
 '8855321',
 '886955',
 '89187',
 '8935689',
 '901690',
 '91476',
 '91477',
 '9188338',
 '91981',
 '92057',
 '9300768',
 '9344385',
 '9447906',
 '9518238',
 '95784',
 '9579634',
 '96276',
 '96279',
 '96482',
 '96594',
 '9777',
 '978920',
 '98233'}

In [8]:
my_books["book_id"] = my_books["book_id"].astype(str)

In [9]:
my_books

,user_id,book_id,rating,title
0,-1,2517439,5,"The Forever War (The Forever War, #1)"
1,-1,113576,5,The Smartest Guys in the Room: The Amazing Ris...
2,-1,35100,5,Battle Cry of Freedom
3,-1,228221,5,The Mask of Command
4,-1,17662739,5,"2001: A Space Odyssey (Space Odyssey, #1)"
...,...,...,...,...
523,-1,28187,1,The Lightning Thief (Percy Jackson and the Ol...
524,-1,7094569,1,"Feed (Newsflesh, #1)"
525,-1,18925933,1,Mastering the VC Game: A Venture Capital Insid...
526,-1,25659450,1,Arkwright
527,-1,82599,1,Rabbits: A Novel

In [10]:
import pandas as pd

data = pd.read_csv("goodreads_interactions.csv")
data

         user_id  book_id  is_read  rating  is_reviewed
0              0      948      1.0     5.0          0.0
1              0      947      1.0     5.0          1.0
2              0      946      1.0     5.0          0.0
3              0      945      1.0     5.0          0.0
4              0      944      1.0     5.0          0.0
...          ...      ...      ...     ...          ...
7555520    15003    13555      1.0     2.0          0.0
7555521    15003     1714      1.0     3.0          0.0
7555522    15003     5436      1.0     2.0          0.0
7555523    15003     1075      0.0     0.0          0.0
7555524    15003      641      NaN     NaN          NaN

[7555525 rows x 5 columns]

In [11]:
overlap_users = {}
# tìm users có đọc những cuốn sách nằm trong liked_books 
with open("goodreads_interactions.csv") as f:
    while True:
        line = f.readline()
        if not line:
            break
        try:
            user_id, csv_id, _, rating, _ = line.strip().split(",")
        except ValueError:
            continue
        
        book_id = csv_book_mapping.get(csv_id)
        
        if book_id in book_set:
            if user_id not in overlap_users:
                overlap_users[user_id] = 1
            else:
                overlap_users[user_id] = overlap_users[user_id] + 1

In [12]:
len(overlap_users)

13322

In [13]:
filtered_overlap_users = set([k for k in overlap_users if overlap_users[k] > my_books.shape[0]/10])

In [14]:
filtered_overlap_users

{'10169',
 '1062',
 '10767',
 '1077',
 '11084',
 '11131',
 '11325',
 '11379',
 '11513',
 '11930',
 '11961',
 '12080',
 '12211',
 '12420',
 '12501',
 '13176',
 '13223',
 '13332',
 '13622',
 '13715',
 '13746',
 '13758',
 '13856',
 '13912',
 '14119',
 '14207',
 '14367',
 '1448',
 '14557',
 '14582',
 '14657',
 '14859',
 '14878',
 '1500',
 '1502',
 '1741',
 '1793',
 '1795',
 '1870',
 '2001',
 '2212',
 '2424',
 '2445',
 '2697',
 '2713',
 '2794',
 '282',
 '2906',
 '2964',
 '2968',
 '2984',
 '3027',
 '3049',
 '3621',
 '3660',
 '394',
 '4106',
 '4574',
 '4594',
 '4635',
 '4936',
 '494',
 '5162',
 '5196',
 '5386',
 '5469',
 '5481',
 '5484',
 '5570',
 '5619',
 '5665',
 '5676',
 '5694',
 '5802',
 '605',
 '6089',
 '6388',
 '648',
 '6496',
 '6678',
 '683',
 '6878',
 '7016',
 '7024',
 '7409',
 '7487',
 '7493',
 '7913',
 '7957',
 '8029',
 '8071',
 '8358',
 '874',
 '910',
 '929',
 '9307',
 '9866',
 '9880',
 '999'}

In [15]:
len(filtered_overlap_users)

99

In [16]:
interactions_list = []

# tìm users có đọc những cuốn sách nằm trong liked_books 
with open("goodreads_interactions.csv", "r") as f:
    while True:
        line = f.readline()
        if not line:
            break
        try:
            user_id, csv_id, _, rating, _ = line.split(",")
        except ValueError:
            continue
        
        
        if user_id in filtered_overlap_users:
            book_id = csv_book_mapping[csv_id]
            interactions_list.append([user_id,book_id,rating])

In [17]:
len(interactions_list)

274468

In [18]:
interactions_list[0]

['282', '627206', '4']

In [19]:
interactions = pd.DataFrame(interactions_list, columns=["user_id","book_id","rating"])

In [20]:
interactions

       user_id   book_id rating
0          282    627206      4
1          282       960      4
2          282     15931      4
3          282     24178      3
4          282      6310      4
...        ...       ...    ...
274463   14878  34670209      4
274464   14878  30251972      0
274465   14878  27917260      0
274466   14878  34831622      0
274467   14878  34657889      2

[274468 rows x 3 columns]

In [21]:
interactions = pd.concat([my_books[["user_id", "book_id", "rating"]], interactions])

In [22]:
interactions

       user_id   book_id rating
0           -1   2517439      5
1           -1    113576      5
2           -1     35100      5
3           -1    228221      5
4           -1  17662739      5
...        ...       ...    ...
274463   14878  34670209      4
274464   14878  30251972      0
274465   14878  27917260      0
274466   14878  34831622      0
274467   14878  34657889      2

[274996 rows x 3 columns]

In [23]:
interactions["book_id"] = interactions["book_id"].astype(str)
interactions["user_id"] = interactions["user_id"].astype(str)
interactions["rating"] = pd.to_numeric(interactions["rating"])

In [24]:
interactions["user_id"].unique()

array(['-1', '282', '394', '494', '605', '648', '683', '874', '910',
       '929', '999', '1062', '1077', '1448', '1500', '1502', '1741',
       '1793', '1795', '1870', '2001', '2212', '2424', '2445', '2697',
       '2713', '2794', '2906', '2964', '2968', '2984', '3027', '3049',
       '3621', '3660', '4106', '4574', '4594', '4635', '4936', '5162',
       '5196', '5386', '5469', '5481', '5484', '5570', '5619', '5665',
       '5676', '5694', '5802', '6089', '6388', '6496', '6678', '6878',
       '7016', '7024', '7409', '7487', '7493', '7913', '7957', '8029',
       '8071', '8358', '9307', '9866', '9880', '10169', '10767', '11084',
       '11131', '11325', '11379', '11513', '11930', '11961', '12080',
       '12211', '12420', '12501', '13176', '13223', '13332', '13622',
       '13715', '13746', '13758', '13856', '13912', '14119', '14207',
       '14367', '14557', '14582', '14657', '14859', '14878'], dtype=object)

In [25]:
interactions["user_index"] = interactions["user_id"].astype("category").cat.codes

In [26]:
len(interactions["user_index"].unique())

100

In [27]:
interactions["book_index"] = interactions["book_id"].astype("category").cat.codes

In [28]:
interactions["book_index"].unique()

array([65768,  7123, 92711, ..., 75664, 92279, 91986])

In [29]:
from scipy.sparse import coo_matrix

ratings_mat_coo = coo_matrix((interactions["rating"], (interactions["user_index"], interactions["book_index"])))

In [30]:
ratings_mat_coo

<100x136929 sparse matrix of type '<class 'numpy.int64'>'
	with 274996 stored elements in COOrdinate format>

In [31]:
ratings_mat = ratings_mat_coo.tocsr()

In [32]:
interactions[interactions["user_id"] == "-1"]

    user_id   book_id  rating  user_index  book_index
0        -1   2517439       5           0       65768
1        -1    113576       5           0        7123
2        -1     35100       5           0       92711
3        -1    228221       5           0       56176
4        -1  17662739       5           0       34870
..      ...       ...     ...         ...         ...
523      -1     28187       1           0       76417
524      -1   7094569       1           0      117830
525      -1  18925933       1           0       43504
526      -1  25659450       1           0       68309
527      -1     82599       1           0      126495

[528 rows x 5 columns]

In [33]:
my_index = 0

In [34]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(ratings_mat[my_index,:], ratings_mat).flatten()

In [42]:
similarity[1]

0.08690135276642397

In [43]:
import numpy as np

indices = np.argpartition(similarity, -15)[-15:]

In [44]:
indices

array([26, 65, 68, 42, 45, 48, 56, 17, 16, 14, 73,  9,  7, 59,  0],
      dtype=int64)

In [45]:
similar_users = interactions[interactions["user_index"].isin(indices)].copy()

In [46]:
similar_users = similar_users[similar_users["user_id"] != "-1"]

In [47]:
similar_users

       user_id   book_id  rating  user_index  book_index
832        394    375802       5          56       95110
833        394        11       5          56        5054
834        394    234225       5          56       59329
835        394     29580       5          56       80535
836        394     77565       5          56      122463
...        ...       ...     ...         ...         ...
252221   14207  22449471       0          26       54210
252222   14207  31431084       0          26       85344
252223   14207  11515328       0          26        8050
252224   14207  29348069       0          26       79701
252225   14207  10942400       4          26        4812

[7905 rows x 5 columns]

In [48]:
book_recs = similar_users.groupby("book_id").rating.agg(["count", "mean"])

In [49]:
book_recs

          count      mean
book_id
1             5  4.600000
10016013      1  5.000000
10031259      2  2.000000
100343        2  2.000000
100344        2  3.500000
...         ...       ...
99452         1  3.000000
99561         1  4.000000
9969571      13  3.615385
9970042       2  4.500000
997354        1  5.000000

[4676 rows x 2 columns]

In [51]:
book_titles = pd.read_json("books_titles.json")
book_titles["book_id"] = book_titles["book_id"].astype(str)

In [53]:
book_recs = book_recs.merge(book_titles, how="inner", on="book_id")

In [54]:
book_recs

,book_id,count,mean,title,ratings,url,cover_image,mod_title
0,1,5,4.600000,Harry Potter and the Half-Blood Prince (Harry ...,1713866,https://www.goodreads.com/book/show/1.Harry_Po...,https://images.gr-assets.com/books/1361039191m...,harry potter and the halfblood prince harry po...
1,10016013,1,5.000000,Harry Potter and the Methods of Rationality,8691,https://www.goodreads.com/book/show/10016013-h...,https://images.gr-assets.com/books/1293582551m...,harry potter and the methods of rationality
2,10031259,2,2.000000,"The Emperor's Edge (The Emperor's Edge, #1)",9804,https://www.goodreads.com/book/show/10031259-t...,https://images.gr-assets.com/books/1327954140m...,the emperors edge the emperors edge 1
3,100343,2,2.000000,The Draco Tavern,1690,https://www.goodreads.com/book/show/100343.The...,https://images.gr-assets.com/books/1316729654m...,the draco tavern
4,100344,2,3.500000,Protector (Known Space),7858,https://www.goodreads.com/book/show/100344.Pro...,https://images.gr-assets.com/books/1403179200m...,protector known space
...,...,...,...,...,...,...,...,...
4638,99452,1,3.000000,"Ogre, Ogre (Xanth #5)",13931,https://www.goodreads.com/book/show/99452.Ogre...,https://images.gr-assets.com/books/1350835009m...,ogre ogre xanth 5
4639,99561,1,4.000000,Looking for Alaska,804587,https://www.goodreads.com/book/show/99561.Look...,https://images.gr-assets.com/books/1394798630m...,looking for alaska
4640,9969571,13,3.615385,Ready Player One,376328,https://www.goodreads.com/book/show/9969571-re...,https://images.gr-assets.com/books/1500930947m...,ready player one
4641,9970042,2,4.500000,"Whispers Under Ground (Peter Grant, #3)",16019,https://www.goodreads.com/book/show/9970042-wh...,https://images.gr-assets.com/books/1341006340m...,whispers under ground peter grant 3
4642,997354,1,5.000000,The Pillars of the Earth,1564,https://www.goodreads.com/book/show/997354.The...,https://images.gr-assets.com/books/1395057247m...,the pillars of the earth

In [57]:
book_recs["adjusted_count"] = book_recs["count"] * (book_recs["count"] / book_recs["ratings"])

In [58]:
book_recs["score"] = book_recs["mean"] * book_recs["adjusted_count"]

In [61]:
book_recs = book_recs[~book_recs["book_id"].isin(my_books["book_id"])]

In [62]:
my_books["mod_title"] = my_books["title"].str.replace("[^a-zA-Z0-9 ]", "", regex=True).str.lower()

In [63]:
my_books["mod_title"] = my_books["mod_title"].str.replace("\s+", "",regex=True)

In [64]:
book_recs = book_recs[~book_recs["mod_title"].isin(my_books["mod_title"])]

In [66]:
book_recs = book_recs[book_recs["count"] > 2]

In [67]:
book_recs = book_recs[book_recs["mean"] > 4]

In [69]:
top_recs = book_recs.sort_values("score", ascending=False)

In [70]:
top_recs

,book_id,count,mean,title,ratings,url,cover_image,mod_title,adjusted_count,score
2382,26367085,3,4.333333,"A Plague of Swords (The Traitor Son Cycle, #4)",1458,https://www.goodreads.com/book/show/26367085-a...,https://images.gr-assets.com/books/1463809721m...,a plague of swords the traitor son cycle 4,0.006173,0.026749
1664,21066604,3,4.666667,"Half the World (Shattered Sea, #2)",1893,https://www.goodreads.com/book/show/21066604-h...,https://images.gr-assets.com/books/1415230868m...,half the world shattered sea 2,0.004754,0.022187
262,11543195,9,4.555556,"Words of Radiance (The Stormlight Archive, #2)",16747,https://www.goodreads.com/book/show/11543195-w...,https://images.gr-assets.com/books/1391535250m...,words of radiance the stormlight archive 2,0.004837,0.022034
2424,27154427,5,4.200000,"The Wheel of Osheim (The Red Queen's War, #3)",5281,https://www.goodreads.com/book/show/27154427-t...,https://images.gr-assets.com/books/1450726066m...,the wheel of osheim the red queens war 3,0.004734,0.019883
3194,3943,3,4.666667,The Hyperion Omnibus: Hyperion / The Fall of H...,2254,https://www.goodreads.com/book/show/3943.The_H...,https://s.gr-assets.com/assets/nophoto/book/11...,the hyperion omnibus hyperion the fall of hype...,0.003993,0.018634
...,...,...,...,...,...,...,...,...,...,...
2166,2493,3,4.333333,The Time Machine,282900,https://www.goodreads.com/book/show/2493.The_T...,https://images.gr-assets.com/books/1327942880m...,the time machine,0.000032,0.000138
4027,7126,4,4.250000,The Count of Monte Cristo,564778,https://www.goodreads.com/book/show/7126.The_C...,https://images.gr-assets.com/books/1309203605m...,the count of monte cristo,0.000028,0.000120
1716,2165,3,4.666667,The Old Man and the Sea,535621,https://www.goodreads.com/book/show/2165.The_O...,https://images.gr-assets.com/books/1329189714m...,the old man and the sea,0.000017,0.000078
2127,24583,3,4.333333,The Adventures of Tom Sawyer,564737,https://www.goodreads.com/book/show/24583.The_...,https://images.gr-assets.com/books/1404811979m...,the adventures of tom sawyer,0.000016,0.000069
0,1,5,4.600000,Harry Potter and the Half-Blood Prince (Harry ...,1713866,https://www.goodreads.com/book/show/1.Harry_Po...,https://images.gr-assets.com/books/1361039191m...,harry potter and the halfblood prince harry po...,0.000015,0.000067

In [71]:
def make_clickable(val):
    return '<a target="_blank" href="{}">Goodreads</a>'.format(val)
def show_image(val):
    return '<img  src="{}" with=50></img>'.format(val)

In [72]:
top_recs.style.format({'url': make_clickable, 'cover_image': show_image})